# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DecimalField(decimal_places=0, max_digits=5)),
                ('sample', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=100)),
            ],
        ),
    ]
