# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_run', models.CharField(max_length=256)),
                ('sample_transmission_run', models.CharField(blank=True, max_length=256, null=True)),
                ('background_run', models.CharField(blank=True, max_length=256, null=True)),
                ('background_transmission_run', models.CharField(blank=True, max_length=256, null=True)),
                ('transmission_run', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='reduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', related_query_name='entry', to='app1.Reduction'),
        ),
    ]
