# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160113_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='background_run',
            field=models.CharField(default=datetime.datetime(2016, 1, 13, 19, 37, 26, 982746, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='background_transmission_run',
            field=models.CharField(default=datetime.datetime(2016, 1, 13, 19, 37, 31, 878057, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 1, 13, 19, 37, 35, 350143, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='sample_transmission_run',
            field=models.CharField(default=datetime.datetime(2016, 1, 13, 19, 37, 38, 333604, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='transmission_run',
            field=models.CharField(default=datetime.datetime(2016, 1, 13, 19, 37, 41, 846526, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reduction',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 1, 13, 19, 37, 45, 845077, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
